before_script:
  - apt-get update

after_script:
  - gradle --version

sid-jdk8:
  image: debian:sid-slim
  script:
    - apt-get -y install openjdk-8-jdk-headless gradle
    - gradle build --stacktrace
  artifacts:
    name: public-transport-enabler-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    paths:
      - build/libs/*.jar

bullseye-jdk11:
  image: debian:bullseye-slim
  script:
    - apt-get -y install openjdk-11-jdk-headless gradle
    - gradle build --stacktrace
  artifacts:
    name: public-transport-enabler-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    paths:
      - build/libs/*.jar

bookworm-jdk17:
  image: debian:bookworm-slim
  script:
    - apt-get -y install openjdk-17-jdk-headless gradle
    - gradle build --stacktrace
  artifacts:
    name: public-transport-enabler-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    paths:
      - build/libs/*.jar
